// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SnackMachine.Logic.Persistence;

#nullable disable

namespace SnackMachine.Logic.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230503080304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SnackMachine.Logic.SnackMachineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SnackMachine", (string)null);
                });

            modelBuilder.Entity("SnackMachine.Logic.SnackMachineEntity", b =>
                {
                    b.OwnsOne("SnackMachine.Logic.Money", "MoneyInside", b1 =>
                        {
                            b1.Property<Guid>("SnackMachineEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("FiveDollarCount")
                                .HasColumnType("integer")
                                .HasColumnName("FiveDollarCount");

                            b1.Property<int>("OneCentCount")
                                .HasColumnType("integer")
                                .HasColumnName("OneCentCount");

                            b1.Property<int>("OneDollarCount")
                                .HasColumnType("integer")
                                .HasColumnName("OneDollarCount");

                            b1.Property<int>("QuarterCount")
                                .HasColumnType("integer")
                                .HasColumnName("QuarterCount");

                            b1.Property<int>("TenCentCount")
                                .HasColumnType("integer")
                                .HasColumnName("TenCentCount");

                            b1.Property<int>("TwentyDollarCount")
                                .HasColumnType("integer")
                                .HasColumnName("TwentyDollarCount");

                            b1.HasKey("SnackMachineEntityId");

                            b1.ToTable("SnackMachine");

                            b1.WithOwner()
                                .HasForeignKey("SnackMachineEntityId");
                        });

                    b.Navigation("MoneyInside")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
